// Generated by LiveScript 1.3.1
(function(){
  var React, App;
  React = require('react');
  App = require('./components/app.ls');
  React.render(<App />, document.getElementById('app'));
}).call(this);
